from __future__ import annotations

from pathlib import Path
from typing import Protocol

from development.models import CodingAgentInfo, CodingAgentResult, CodingTask


class CodingAgent(Protocol):
    id: str
    name: str
    provider: str

    def detect(self) -> CodingAgentInfo: ...
    def health(self) -> CodingAgentInfo: ...
    def capabilities(self) -> dict: ...
    def start(self, workspace: Path, task: CodingTask) -> CodingAgentResult: ...
    def send_task(self, task: CodingTask) -> CodingAgentResult: ...
    def inspect_output(self) -> dict: ...
    def stop(self) -> dict: ...
    def collect_result(self) -> CodingAgentResult: ...
